export { default as HomeLayout } from './HomeLayout'
export { default as Landing } from './Landing'
export { default as Services } from './Services'
export { default as Moving } from './Moving'
export { default as Contact } from './Contact'
